version: '3.7'

networks:
  conta-corrent-network:
    driver: bridge


services:
  db:
    image: postgres
    networks:
      - conta-corrent-network
    environment:
      POSTGRES_DB: conta-corrent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  conta-corrent-api:
    build:
      context: "."
      dockerfile: ".docker/Dockerfile"
    networks:
      - conta-corrent-network
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./.gocache:/go
      - ./.ssh:/root/.ssh
      - ./:/opt/app/api
    ports:
      - '5055:5055'